# Generated by Django 5.2.7 on 2025-11-01 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'comuna',
            },
        ),
        migrations.CreateModel(
            name='Moto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=10, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('anio', models.PositiveIntegerField(db_column='anio', verbose_name='año')),
                ('tipo', models.CharField(max_length=20)),
                ('disponible', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'moto',
            },
        ),
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('telefono', models.CharField(max_length=15)),
                ('correo', models.EmailField(max_length=100)),
                ('licencia', models.CharField(choices=[('C1', 'Clase C1'), ('C2', 'Clase C2'), ('C3', 'Clase C3')], max_length=20)),
                ('estado', models.CharField(default='Activo', max_length=20)),
                ('fecha_ingreso', models.DateField()),
            ],
            options={
                'db_table': 'motorista',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'region',
            },
        ),
        migrations.CreateModel(
            name='ReporteMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DIARIO', 'Reporte Diario'), ('MENSUAL', 'Reporte Mensual'), ('ANUAL', 'Reporte Anual')], max_length=10)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('generado_por', models.CharField(max_length=100)),
                ('total_movimientos', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'reporte_movimiento',
            },
        ),
        migrations.CreateModel(
            name='Farmacia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=15)),
                ('correo', models.EmailField(max_length=100)),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='App.comuna')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='App.region')),
            ],
            options={
                'db_table': 'farmacia',
            },
        ),
        migrations.CreateModel(
            name='AsignacionMoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('moto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.moto')),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.motorista')),
            ],
            options={
                'db_table': 'asignacion_moto',
            },
        ),
        migrations.CreateModel(
            name='AsignacionFarmacia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('farmacia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.farmacia')),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.motorista')),
            ],
            options={
                'db_table': 'asignacion_farmacia',
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('tipo', models.CharField(choices=[('DIRECTO', 'Movimiento Directo'), ('RECETA', 'Movimiento con Receta'), ('TRASLADO', 'Movimiento con Traslado'), ('REENVIO', 'Movimiento con Reenvío')], max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('EN_PROCESO', 'En proceso'), ('COMPLETADO', 'Completado'), ('ANULADO', 'Anulado')], default='EN_PROCESO', max_length=20)),
                ('farmacia_destino', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_destino', to='App.farmacia')),
                ('farmacia_origen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_origen', to='App.farmacia')),
                ('moto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.moto')),
                ('motorista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.motorista')),
            ],
            options={
                'db_table': 'movimiento',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.AddField(
            model_name='comuna',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunas', to='App.region'),
        ),
    ]
