# Generated by Django 5.2.7 on 2025-11-02 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmacia',
            name='comuna',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='farmacia',
            name='region',
            field=models.CharField(choices=[('Arica y Parinacota', 'Arica y Parinacota'), ('Tarapacá', 'Tarapacá'), ('Antofagasta', 'Antofagasta'), ('Atacama', 'Atacama'), ('Coquimbo', 'Coquimbo'), ('Valparaíso', 'Valparaíso'), ('Metropolitana de Santiago', 'Metropolitana de Santiago'), ("Libertador General Bernardo O'Higgins", "Libertador General Bernardo O'Higgins"), ('Maule', 'Maule'), ('Ñuble', 'Ñuble'), ('Biobío', 'Biobío'), ('La Araucanía', 'La Araucanía'), ('Los Ríos', 'Los Ríos'), ('Los Lagos', 'Los Lagos'), ('Aysén del General Carlos Ibáñez del Campo', 'Aysén del General Carlos Ibáñez del Campo'), ('Magallanes y de la Antártica Chilena', 'Magallanes y de la Antártica Chilena')], max_length=100),
        ),
        migrations.AlterModelOptions(
            name='farmacia',
            options={'verbose_name': 'Farmacia', 'verbose_name_plural': 'Farmacias'},
        ),
        migrations.AddField(
            model_name='farmacia',
            name='provincia',
            field=models.CharField(default='Desconocida', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Comuna',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
