# Generated by Django 5.2.7 on 2025-11-02 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_farmacia_comuna_alter_farmacia_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorista',
            name='farmacia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.farmacia'),
        ),
        migrations.AddField(
            model_name='motorista',
            name='moto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.moto'),
        ),
    ]
