# Generated by Django 5.1.5 on 2025-11-04 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_motorista_farmacia_motorista_moto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moto',
            name='tipo',
        ),
    ]
