# Generated by Django 5.2.7 on 2025-11-15 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_remove_moto_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimiento',
            name='farmacia_destino',
        ),
        migrations.AddField(
            model_name='movimiento',
            name='destino',
            field=models.CharField(default='Sin destino registrado', max_length=200),
            preserve_default=False,
        ),
    ]
